# config for pre-mRNA quantification snakemake pipeline #


# directory with fastqs and generated data
DATA: 
    "../data-rerun"

# directory for auxillary scripts
SRC: 
  "../src" 

# directory for R scripts
RSRC:
  "../R"

  # directory for databases
DBASES: 
    "../dbases-rerun" 

GENOMES:
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xentrop9.1/xenTro9.fa"

TRANSCRIPTS:
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/annotation/xenopus/jgi_xentrop9.1/xenTro9.gtf"

#INTRONS:
    #    drosophila: "/beevol/home/riemondy/Projects/mzt-introns/dbases/drosophila/saf/fly_introns.saf"

#EXONS:
    #    drosophila: "/beevol/home/riemondy/Projects/mzt-introns/dbases/drosophila/saf/fly_exons.saf"

CHROM_SIZES:
    zebrafish:  "/beevol/home/riemondy/Projects/shared_dbases/genomes/zebrafish/danRer10/danRer10.fa.fai"

GENOME_DIRS:
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/star/xenopus/jgi_xentrop9.1"

SALMON_K:
    xenopus_t: 31

OWENS_RIBO:
    trim: " "
    intron_count: " --minOverlap 5 -s 0 -p "
    exon_count: " --fracOverlap 1 -s 0 -p "
    map: " -l ISR "
    idx: " -k 31 "
    stranded: "reverse"
    bt_map: " --nofw "
    fq: 
        - "_1.fastq.gz"
        - "_2.fastq.gz"

T0_SAMPLES: 
    - "SRR1795631"

T0_EXPT: "OWENS_RIBO"

LIB_PARAMS: "frog_ribozero_lib_params.tsv"
