# config for pre-mRNA quantification snakemake pipeline #
 
# directory for data
DATA: 
  "../data"

# directory for auxillary scripts
SRC: 
  "../src" 

# directory for databases
DBASES: 
  "../dbases" 

MMR: "/beevol/home/riemondy/src/mmr/mmr"

GENOMES:
    drosophila: "/beevol/home/riemondy/Projects/shared_dbases/genomes/drosophila/Drosophila_melanogaster.BDGP6.dna.toplevel.fa"
    xenopus:  "/beevol/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xenla9.2/XL9_2.fa"
    zebrafish:  "/beevol/home/riemondy/Projects/shared_dbases/genomes/zebrafish/danRer10/danRer10.fa"
    seaurchin:  "/beevol/home/riemondy/Projects/mzt-introns/dbases/seaurchin/GCF_000002235.4_Spur_4.2_genomic.fa"
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xentrop9.1/xenTro9.fa"
    human: "/beevol/home/riemondy/Projects/shared_dbases/genomes/GRCh38.primary_assembly.genome.fa"
    mouse: "/beevol/home/riemondy/Projects/shared_dbases/genomes/GRCm38.primary_assembly.genome.fa"

TRANSCRIPTS:
    drosophila: "/beevol/home/riemondy/Projects/shared_dbases/annotation/drosophila/Drosophila_melanogaster.BDGP6.84.gtf"
    xenopus: "/beevol/home/riemondy/Projects/shared_dbases/annotation/xenopus/jgi_xenla9.2/XENLA_9.2_Xenbase.gtf"
    zebrafish: "/beevol/home/riemondy/Projects/shared_dbases/annotation/zebrafish/danRer10/danRer10.gtf"
    seaurchin:  "/beevol/home/riemondy/Projects/mzt-introns/dbases/seaurchin/GCF_000002235.4_Spur_4.2_genomic.gtf"
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/annotation/xenopus/jgi_xentrop9.1/xenTro9.gtf"
    human: "/beevol/home/riemondy/Projects/shared_dbases/annotation/gencode.v26.primary_assembly.annotation.gtf"
    mouse: "/beevol/home/riemondy/Projects/shared_dbases/annotation/gencode.vM15.primary_assembly.annotation.gtf"

INTRONS:
    drosophila: "/beevol/home/riemondy/Projects/mzt-introns/dbases/drosophila/saf/fly_introns.saf"
    zebrafish: "/beevol/home/riemondy/Projects/mzt-introns/dbases/zebrafish/saf/introns.saf"
    xenopus_t: "/beevol/home/riemondy/Projects/mzt-introns/dbases/xenopus_t/saf/introns.saf"
EXONS:
    drosophila: "/beevol/home/riemondy/Projects/mzt-introns/dbases/drosophila/saf/fly_exons.saf"
    zebrafish: "/beevol/home/riemondy/Projects/mzt-introns/dbases/zebrafish/saf/exons.saf"
    xenopus_t: "/beevol/home/riemondy/Projects/mzt-introns/dbases/xenopus_t/saf/exons.saf"

CHROM_SIZES:
    drosophila: "/beevol/home/riemondy/Projects/shared_dbases/genomes/drosophila/Drosophila_melanogaster.BDGP6.dna.toplevel.fa.fai"
    xenopus:  "/beevol/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xenla9.2/XL9_2.fa.fai"
    zebrafish:  "/beevol/home/riemondy/Projects/shared_dbases/genomes/zebrafish/danRer10/danRer10.fa.fai"
    seaurchin:  "/beevol/home/riemondy/Projects/mzt-introns/dbases/seaurchin/GCF_000002235.4_Spur_4.2_genomic.fa.fai"
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xentrop9.1/xenTro9.fa.fai"
    human: "/beevol/home/riemondy/Projects/shared_dbases/genomes/GRCh38.primary_assembly.genome.fa.fai"
    mouse: "/beevol/home/riemondy/Projects/shared_dbases/genomes/GRCm38.primary_assembly.genome.fa.fai"

GENOME_DIRS:
    drosophila: "/beevol/home/riemondy/Projects/shared_dbases/star/drosophila/BDGP6"
    xenopus: "/beevol/home/riemondy/Projects/shared_dbases/star/xenopus/jgi_xenla9.2"
    zebrafish: "/beevol/home/riemondy/Projects/shared_dbases/star/zebrafish/danRer10"
    seaurchin: "/beevol/home/riemondy/Projects/shared_dbases/star/seaurchin/Spur_4.2"
    xenopus_t: "/beevol/home/riemondy/Projects/shared_dbases/star/xenopus/jgi_xentrop9.1"
    human: "/beevol/home/riemondy/Projects/shared_dbases/star/gencode_GRCh38"
    mouse: "/beevol/home/riemondy/Projects/shared_dbases/star/gencode_GRCm38"

SALMON_K:
    drosophila: 21
    xenopus: 21
    zebrafish: 31
    seaurchin: 31
    xenopus_t: 31 
    human: 31

# path to STAR SJ.out.tab file
# Can be single file or wildcard expression matching multiple files
SPLICE_JUNCTS:
  "../data/star/firstpass/*_SJ.out.tab"

EICHHORN:
    trim: " -q 10 -a 'TCGTATGCCGTCTTCTGCTT' -u 8 "
    intron_count: " --minOverlap 5 -s 1 "
    exon_count: " --fracOverlap 1 -s 1 "
    map: " --fldMean 40 --fldSD 4 --libType 'SF' "
    stranded: "forward"
    idx: " -k 21 "
    bt_map: " --norc "
    fq: 
        - ".fastq.gz"

RISSLAND:
    trim: " -q 10 -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC' "
    intron_count: " --minOverlap 5 -s 2 "
    exon_count: " --fracOverlap 1 -s 2 "
    map: " --fldMean 200 --fldSD 20 --libType 'SR' "
    idx: " -k 21 "
    stranded: "reverse"
    bt_map: " --nofw "
    fq: 
        - ".fastq.gz"

WHITE:
    trim: " "
    intron_count: " --minOverlap 5 -s 2 -p "
    exon_count: " --fracOverlap 1 -s 2 -p "
    map: " -l ISR  --discardOrphansQuasi "
    idx: " -k 31 "
    fq: 
        - "_1.fastq.gz"
        - "_2.fastq.gz"

TU:
    trim: " "
    map: " -l IU "
    fq:
        - "_1.fastq.gz"
        - "_2.fastq.gz"

OWENS:
    trim: " "
    intron_count: " --minOverlap 5 -s 0 -p "
    exon_count: " --fracOverlap 1 -s 0 -p "
    map: " -l ISR  --discardOrphansQuasi "
    idx: " -k 31 "
    fq: 
        - "_1.fastq.gz"
        - "_2.fastq.gz"

XUE:
    trim: " "
    intron_count: " --minOverlap 5 -s 0 -p "
    exon_count: " --fracOverlap 1 -s 0 -p "
    map: " -l ISR  --discardOrphansQuasi "
    idx: " -k 31 "
    fq: 
        - "_1.fastq.gz"
        - "_2.fastq.gz"
