# config for pre-mRNA quantification snakemake pipeline #
 
# directory for data
DATA: 
  "../data"

# directory for auxillary scripts
SRC: 
  "../src" 

# directory for databases
DBASES: 
  "../dbases" 

GENOMES:
    drosophila: "/vol3/home/riemondy/Projects/shared_dbases/genomes/drosophila/Drosophila_melanogaster.BDGP6.dna.toplevel.fa"
    xenopus:  "/vol3/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xenla9.2/XL9_2.fa"
    zebrafish:  "/vol3/home/riemondy/Projects/shared_dbases/genomes/zebrafish/GRCz10/Danio_rerio.GRCz10.dna.toplevel.fa"

TRANSCRIPTS:
    drosophila: "/vol3/home/riemondy/Projects/shared_dbases/annotation/drosophila/Drosophila_melanogaster.BDGP6.84.gtf"
    xenopus: "/vol3/home/riemondy/Projects/shared_dbases/annotation/xenopus/jgi_xenla9.2/XENLA_9.2_Xenbase.gtf"
    zebrafish: "/vol3/home/riemondy/Projects/shared_dbases/annotation/zebrafish/GRCz10/Danio_rerio.GRCz10.91.gtf"

CHROM_SIZES:
    drosophila: "/vol3/home/riemondy/Projects/shared_dbases/genomes/drosophila/Drosophila_melanogaster.BDGP6.dna.toplevel.fa.fai"
    xenopus:  "/vol3/home/riemondy/Projects/shared_dbases/genomes/xenopus/jgi_xenla9.2/XL9_2.fa.fai"
    zebrafish:  "/vol3/home/riemondy/Projects/shared_dbases/genomes/zebrafish/GRCz10/Danio_rerio.GRCz10.dna.toplevel.fa.fai"

GENOME_DIRS:
    drosophila: "/vol3/home/riemondy/Projects/shared_dbases/star/drosophila/BDGP6"
    xenopus: "/vol3/home/riemondy/Projects/shared_dbases/star/xenopus/jgi_xenla9.2"
    zebrafish: "/vol3/home/riemondy/Projects/shared_dbases/star/zebrafish/GRCz10"


# path to STAR SJ.out.tab file
# Can be single file or wildcard expression matching multiple files
SPLICE_JUNCTS:
  "../data/star/firstpass/*_SJ.out.tab"

EICHHORN:
    trim: " -q 10 -a 'TCGTATGCCGTCTTCTGCTT' -u 8 "
    map: " --fldMean 40 --fldSD 4 --libType 'SF' --seqBias --gcBias "
    fq: 
        - ".fastq.gz"

RISSLAND:
    trim: " -q 10 -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC' "
    map: " --fldMean 200 --fldSD 20 --libType 'SR' --seqBias --gcBias "
    fq: 
        - ".fastq.gz"

WHITE:
    trim: " "
    map: " -l ISR "
    fq: 
        - "_1.fastq.gz"
        - "_2.fastq.gz"
