# config for MZT intron quantification snakemake pipeline #


# directory with fastqs and generated data
DATA: 
    "../data-test"

# directory for output databases
DBASES: 
    "../dbases-test" 

# genome fasta file
GENOMES:
    drosophila: "../dbases-test/drosophila/ext/Drosophila_melanogaster.BDGP6.dna.2L.fa"

# transcript annotation in GTF format
TRANSCRIPTS:
    drosophila: "../dbases-test/drosophila/ext/Drosophila_melanogaster.BDGP6.84.2L.gtf"

# intron annotation in SAF format 
# leave blank if traditional alignment approach not needed
INTRONS:
    drosophila: ""

EXONS:
    drosophila: ""

# fasta index file
CHROM_SIZES:
    drosophila: "../dbases-test/drosophila/ext/Drosophila_melanogaster.BDGP6.dna.2L.fa.fai"

# Path to star index, or desired path for star index to be built by pipeline,
# only built if traditional alignment approach is needed
GENOME_DIRS:
    drosophila: "../dbases-test/drosophila/star/BDGP6"

# experiment specific settings
# trim: settings for cutadapt
# intron/exon_count: settings for featureCounts, only run if introns/exons
# defined above
# stranded: either forward of reverse
# map: additional settings for salmon quantification
# bt_map: additional settings for bowtie2 mapping  
# fq: suffix for R1 and R2
#
TESTDATA:
    trim: " -q 10 -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC' "
    intron_count: " --minOverlap 10 -s 2 "
    exon_count: " --fracOverlap 1 -s 2 "
    map: " --fldMean 200 --fldSD 20 --libType 'SR' "
    stranded: "reverse"
    bt_map: " --nofw "
    fq: 
        - ".fastq.gz"

# sample names that indicate samples from the earliest timepoint in the timecourse
# (e.g. a zygote or other pre-ZGA sample). 
T0_SAMPLES:
    - "SRR5469986.sub"
    - "SRR5469998.sub"

# Path to file with library definitions
LIB_PARAMS: "test_lib_params.tsv"

# directory for auxillary scripts
SRC: 
  "../src" 

# directory for R scripts
RSRC:
  "../R"

# memory allocation (MB) for default rules, or higher memory processes
MALLOC:
  DEFAULT: "4096"
  SALMON: "8192"
  STAR: "36864"

CLUSTER: "LSF"
