## Install Bioconductor packages
BiocManager::install(c("Biostrings",
                       "GenomicRanges",
                       "GenomicAlignments", 
                       "GenomicFeatures",
                       "Gviz",
                       "eisaR", 
                       "ComplexHeatmap",
                       "DESeq2", 
                       "rtracklayer", 
                       "tximport", 
                       "Rsubread", 
                       "Rhtslib", 
                       "zlibbioc", 
                       "BiocParallel"), 
                     suppressUpdates=TRUE, 
                     ask=FALSE, 
                     version = "3.15")

install.packages(c('dplyr', 
                   'purrr', 
                   'readr', 
                   'stringr', 
                   'valr', 
                   'purrr', 
                   'Matrix', 
                   'RColorBrewer', 
                   'cowplot', 
                   'doParallel', 
                   'ggplot2', 
                   'ggrepel', 
                   'here', 
                   'jsonlite', 
                   'readxl', 
                   'tibble', 
                   'tidyr', 
                   'viridis',
                   'eulerr')) 
