---
title: "Zelda Binding"
author: "Kent Riemondy RBI"
date: "4/6/2018"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = FALSE)
```

```{r libs}
library(valr)
library(tidyverse)
library(rtracklayer)
library(doParallel)
source("../../R/globals.r")
```

## Examine zelda binding


```{r eisen_dat}
zelda_chip <- read_tsv("https://doi.org/10.1371/journal.pgen.1002266.s007", 
              col_names = T, 
              skip = 1)

zelda_peaks <- dplyr::select(zelda_chip,
                             chrom = Chr, 
                             start = From,
                             end = To,
                             gene = TSS_gene,
                             dist = TSS_dist,
                             score = Height)

zelda_10k <- zelda_peaks %>% filter(dist <= 10000)
zelda_10k_summed <- group_by(zelda_10k, gene) %>% summarize(binding_sites = n(),
                                                            score = mean(score))
```

```{r diff_genes}
de_res <- read_tsv("../2018-02-20/all_genes_2018-03-29.tsv")

de_res <- left_join(de_res,
                    zelda_10k_summed,
                    by = c("gene_name" = "gene")) %>% 
  mutate(binding_sites = ifelse(is.na(binding_sites),
                                0,
                                binding_sites),
         score = ifelse(is.na(score),
                        0,
                        score))
   #      score = log2(score + 1))

clusters <- read_tsv("../2018-02-20/fly_pre_km_clusters.tsv")

de_res <- left_join(de_res, clusters, by = c("gene_id", "gene_name"))

counts_cols <- read_tsv("../2018-02-20/fly_pre_norm_counts.tsv", col_names = F, n_max = 1)
counts <- read_tsv("../2018-02-20/fly_pre_norm_counts.tsv", col_names = F, skip = 1)
colnames(counts) <- c("gene_id", counts_cols)
counts <- as.data.frame(counts)
rownames(counts) <- counts[, 1]
counts[, 1] <- NULL

zscores <- t(scale(t(log2(counts + 1))))

cluster_res <- de_res %>% filter(!is.na(cluster))
annotation_data <- cluster_res[, c("gene_id", "score", "binding_sites", "cluster")] %>% as.data.frame()
rownames(annotation_data) <- annotation_data[, 1]
annotation_data[, 1] <- NULL
```

```{r hmaps}
library(ComplexHeatmap)
library(circlize)

ht <- Heatmap(zscores[rownames(annotation_data), ],
              name = "pre-mRNA \nZscore",
              split = annotation_data$cluster,
              show_row_names = F,
              show_row_dend = F)

ha <- HeatmapAnnotation(annotation_data[, c("score", "binding_sites")],
                        col = list(
                          score = colorRamp2(c(0, max(annotation_data$score, na.rm = T)), 
                                             c("white", "darkred")),
                          binding_sites = colorRamp2(c(0, max(annotation_data$binding_sites, 
                                                              na.rm = T)), c("white", "darkblue"))),
                        which = "row", width = unit(1, "cm"),
                        annotation_legend_param = list(score = list(title = "Zelda\nbinding\nscore"),
                                                       binding_sites = list(title = "N Zelda\nbinding\nsites")))
ht + ha

pdf("zelda_binding_premRNA_clusters.pdf")
print(ht + ha)
dev.off()
```

```{r cluster_4_genes}
de_res %>% 
  filter(cluster == 4) %>% 
  arrange(`padj_pre-mRNA`)

genes_to_query <- de_res %>% 
  filter(cluster == 4) %>% 
  arrange(`padj_pre-mRNA`) %>% 
  pull(gene_id)

library(kentr)
gtffile <- "~/Projects/shared_dbases/annotation/drosophila/Drosophila_melanogaster.BDGP6.84.gtf"

get_3utrs <- function(gtf_file, gene_ids, gene_col = "gene_id", transcript_col = "transcript_id"){
  gtf <- import(gtf_file)
  gtf <- as.data.frame(gtf)
  gtf <- filter(gtf, gene_id %in% gene_ids)
  gtf <- dplyr::select(gtf, 
                       chrom = seqnames, 
                       start, end, type, strand, exon_id, one_of(c(gene_col, transcript_col)))
  gtf <- dplyr::filter(gtf, 
                       type %in% c("exon", "CDS"))
  cds_gtf <- filter(gtf, type == "CDS") %>% 
         group_by(transcript_id) %>% 
         summarize(cds_start = unique(ifelse(strand == "+",
                                  min(start), 
                                  max(end))),
                   cds_end = unique(ifelse(strand == "+", 
                                max(end),
                                min(start)))) %>% 
    left_join(gtf, ., by = "transcript_id")
  
  cds_gtf <- cds_gtf %>% 
    filter(type == "exon") %>% 
    group_by(transcript_id) %>% 
    mutate(., start = ifelse(strand == "+", cds_end, start), 
              end = ifelse(strand == "+", end, cds_start)) %>%
    ungroup() %>% 
    select(chrom:transcript_id)  %>%
    filter(start <= end)
  
  res <- group_by(cds_gtf, gene_id, strand) %>% 
    bed_merge() %>% 
    ungroup()
  res
}

genome_file <- "~/Projects/shared_dbases/genomes/drosophila/Drosophila_melanogaster.BDGP6.dna.toplevel.fa"

utrs <- get_3utrs(gtffile, de_res$gene_id)
utr_seqs <- kentr::get_sequences(utrs, genome_file)

#kmers <- mutate(utr_seqs, 
#                kmers = get_kmers(seq, n = 6)) %>% 
#                select(gene_id, start, end, kmers) %>% 
#  unnest()
#
#cluster_ids <- select(cluster_res, cluster, gene_id)
#kmers <- left_join(kmers, cluster_ids, by = "gene_id")
#
### calc utr length and sum multiple exons per utr
#kmers <- mutate(kmers,
#                exon_len = end - start) %>% 
#  group_by(gene_id, kmer, cluster) %>% 
#  summarize(counts = sum(counts),
#            utr_len = sum(exon_len))
#
#kmers <- ungroup(kmers)
#
#missing_kmers <- expand.grid(rep(list(c("A", "T", "C", "G")), 6)) %>%
#  apply(. , 1, function(x) str_c(x, collapse = "")) %>% 
#  data_frame(kmer = .)
#
#missing_kmers <- crossing(kmer = missing_kmers$kmer, 
#                          gene_id = de_res$gene_id) %>% 
#  left_join(de_res[, c("gene_id", "cluster")], 
#            by = "gene_id")
#
#kmers <- left_join(missing_kmers, 
#                   kmers, by = c("kmer", "gene_id", "cluster"))
#rm(missing_kmers)
#
#kmers <- mutate(kmers, 
#                kmer_density = ifelse(is.na(counts),
#                                      0,
#                                      counts / utr_len))
#
#mer6_summary <- group_by(kmers, cluster, kmer) %>% 
#  summarize(kmer_density = mean(counts, na.rm = T)) %>% 
#  ungroup()
#
#mer6_summary <- mutate(mer6_summary,
#                       cluster = ifelse(is.na(cluster),
#                                        "background",
#                                        as.character(cluster)))
#mer6_summary <- spread(mer6_summary, cluster, kmer_density)

```


