---
title: "MZT differential expression vignette"
author: "Kent Riemondy RBI"
date: '`r Sys.Date()`'
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(here)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyr)
library(tibble)
library(rtracklayer)
library(tximport)
library(DESeq2)
```

## Approach

```{r}
salmon_dir <- "../data-test/salmon_bt2_masked/drosophila/TESTDATA/eisa_masked/"

sr_ids <- c("SRR5469986.sub",
            "SRR5469988.sub",
            "SRR5469990.sub",
            "SRR5469992.sub",
            "SRR5469994.sub",
            "SRR5469998.sub",
            "SRR5470000.sub",
            "SRR5470002.sub",
            "SRR5470004.sub",
            "SRR5470006.sub")

stage <- c("0-1 hr embryo",
            "1-2 hr embryo",
            "2-3 hr embryo",
            "3-4 hr embryo",
            "4-5 hr embryo",
            "0-1 hr embryo",
            "1-2 hr embryo",
            "2-3 hr embryo",
            "3-4 hr embryo",
            "4-5 hr embryo")

strain <- rep(c("w1118", "eGFP-ME31B"), each = 5)

mdata <- data.frame(sr_ids, stage, strain)
```


```{r }
gtf_fn <- "../dbases-test/drosophila/ext/Drosophila_melanogaster.BDGP6.84.2L.gtf"
gtf <- import(gtf_fn) %>% 
  as.data.frame() %>% 
  dplyr::rename(chrom = seqnames) %>% 
  mutate(start = start - 1L)

gene2symbol <- gtf %>%
  filter(type == "gene") %>% 
  select(gene_id, gene_name) %>% 
  distinct()

gene2tx <- gtf %>%
   filter(type == "transcript") %>%
   select(gene_id, transcript_id) %>%
   na.omit() %>%
   distinct()

gene2intron <- read_tsv("../dbases-test/drosophila/eisa/tx2gene.tsv") 
```


## Plot pre-mRNA ratios

```{r}
salmon_files <- file.path("../data-test",
                   "salmon_bt2_masked", 
                   "drosophila",
                   "TESTDATA",
                   "eisa_masked",
                   mdata$sr_ids,
                   "quant.sf")

txi <- tximport(salmon_files, 
                type = "salmon",
                tx2gene = gene2intron)

tpms <- txi$abundance %>% 
  as.data.frame() 
colnames(tpms) <- mdata$sr_ids
tpms <- rownames_to_column(tpms, "feature_id") %>% 
  mutate(count_type = ifelse(str_detect(feature_id, "-I[0-9]*$"),
                             "intron",
                             "exon"),
         gene_id = str_remove(feature_id, "-I[0-9]*$")) %>% 
  select(-feature_id) %>% 
  pivot_longer(cols = -c(count_type, gene_id),
               names_to = "run",
               values_to = "TPM")

tpms <- left_join(tpms, mdata, by = c('run' = 'sr_ids'))
```

```{r}
tpm_summary <- pivot_wider(tpms, 
                           names_from = count_type, 
                           values_from = TPM) %>% 
  na.omit() %>% 
  mutate(intron_ratio  = intron / (intron + exon))

## calc mean primary ratio across developmental stages
tpm_means <- tpm_summary %>% 
  group_by(gene_id, 
           stage) %>% 
  summarize(mean_primary = mean(intron_ratio, na.rm = T)) 

dev_stages_ordered <- c(
  "0-1 hr embryo",
  "1-2 hr embryo",
  "2-3 hr embryo",
  "3-4 hr embryo",
  "4-5 hr embryo")

tpm_means <- mutate(tpm_means, 
                       stage = factor(stage, 
                                      levels = dev_stages_ordered)
                       )

p <- ggplot(tpm_means, 
       aes(stage, mean_primary)) +
  geom_boxplot(outlier.shape = NA, coef = 1e10) + 
  labs(x = "",
       y = expression(frac("Intron TPM", 
                           "Intron + Exon TPM"))) +
  theme(
    axis.text.x = element_text(angle = 90,
                               vjust = 0.5,
                               hjust = 0.5)
  )

p
```


## DE testing

Run deseq2 comaring the post-mzt samples to the pre-mzt.

```{r}
mdata$mzt <- ifelse(mdata$stage %in% c("0-1 hr embryo", "1-2 hr embryo"),
                    "maternal",
                    "zygotic")
ddobj <- DESeqDataSetFromTximport(txi, 
                                  mdata, 
                                  ~mzt + strain)
ddobj <- DESeq(ddobj)

res <- results(ddobj, 
                   name = "mzt_zygotic_vs_maternal", 
                   tidy = T) %>% 
  as_tibble() %>% 
  mutate(count_type = ifelse(str_detect(row, "-I[0-9]*$"), 
                             "intron",
                             "exon"),
         sig = ifelse(padj < 0.05 & log2FoldChange > 0, "Up", 
                      ifelse(padj < 0.05 & log2FoldChange < 0,
                             "Down", "Not Sig"))) %>% 
  filter(!is.na(sig))

out_tbl <- res %>% 
   mutate(gene_id = str_remove(row, "-I[0-9]*$")) %>% 
   left_join(gene2symbol, by = "gene_id")

out_tbl
```

```{r}
ggplot(out_tbl, aes(baseMean, log2FoldChange)) +
  geom_point(aes(color = count_type)) +
  scale_x_log10(labels = scales::comma) +
  scale_color_manual(values = c("grey", "blue"))
```

```{r}
sessionInfo()
```

