name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rnabioco/mzt-introns:latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      
    - name: Download references
      run: |
        cd dbases-test/drosophila/ext; bash ./dl_dbases.sh; ls -l ; cd -
    - name: Test pipeline
      run: |
        cd pipeline; snakemake -npr --configfile config-test.yaml ; cd -
        
    - name: Run pipeline
      run: | 
        cd pipeline; bash snakecharmer-local.sh
    
        
        
